### ISSUE TITLE
Copy/paste keyframes - level 1

### ISSUE THREAD

**Issue by AriaMinaei** [theatre-js/theatre#104]
Scope: Being able to copy/paste keyframes over a single track (i.e. won't be able to copy/paste over compound props, just primitive props).

**Comment by vezwork** [comment]
Notes:
- keyframes can be selected by `ctrl`+`click`+`drag`.
- for level 1, only one track of keyframes will be copy+pastable at a time.
- keyframes on one type of track can be pasted onto any other type of track, but the keyframe values will not be used, the default values for that type will be used instead until the keyframe value is changed.
  - e.g. if two connected boolean keyframes true and false are selected by the user, then copied by the user, then the user clicks on a track with number type keyframes and pastes, the boolean keyframes will be pasted but the keyframes will fall back to the default number value for the type of that track.
  - Falling back to the default value already occurs when a track has a type that does not match the keyframe.
- for level 1, copying and pasting will be done via the context menu.
