### ISSUE TITLE
Contribution doc for cloning repo

### ISSUE THREAD

**Issue by Saspect-IO** [theatre-js/theatre#117]
**Current issue:**
Instructions for cloning repo in the `CONTRIBUTING.md` points to `AriaMinaei` as seen below;
```sh
$ git clone git@github.com:AriaMinaei/theatre.git
$ cd theatre
```

This understandably yields a permission error:
```sh
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Suggested instructions:**

You can fork the repo then:

```sh
# for SSH:
$ git clone git@github.com:<github-username>/theatre.git 
# for HTTPS:
$ git clone https://github.com/<github-username>/theatre.git  

$ cd theatre
```

**Comment by vezwork** [comment]
Thanks for pointing out this issue @Saspect-IO and thanks for the suggestion :) I will implement your suggested change in the next couple days as I am in the process of updating documentation.

**Comment by vezwork** [comment]
Hi @Saspect-IO I've added your suggested change to CONTRIBUTING! If you have some extra time, take a look :) closing this issue.
