### ISSUE TITLE
Increase the maximum zoom on the timeline

### ISSUE THREAD

**Issue by hugeen** [theatre-js/theatre#192]
I would like to design micro animations (~250ms) but the current maximum zoom level is making it difficult for me right now.

I only have access to a very small area on my screen to place my keyframes because the maximum zoom shows 10 seconds on my screen.

I'd like to have a full second taking the whole width of my screen (or even less).

If you don't want to change the default behavior, maybe you can add an option to the initialization?

Something like : 
```javascript
studio.initialize({maxZoom: 0.1})
```

My workaround for now is to consider 1 second as 1/10 second and `play({rate: 10})`

**Comment by AriaMinaei** [comment]
Hi, here is a [quick video](https://www.loom.com/share/b8ed780f70684c4f91dedb7334205c2c) on how to zoom further.

**Comment by hugeen** [comment]
Thank you very much !
