### ISSUE TITLE
R3F Extension bundle ships with @react-three/fiber and @react-three/drei 

### ISSUE THREAD

**Issue by juniorxsound** [theatre-js/theatre#246]
## What?
When building the `@theatre/r3f` extension we don't externalize `@react-three/{fiber|drei}` and they end up in the bundle of the extension. 

## Why?
Since it is expected that the consuming client would install these it could create unexpected bugs with multiple (and different) versions of fiber and drei installed. This also adds about 200kb of unnecessary deps

## Where?
- [ ] These `externals` are commented out in the extension bundle [here](https://github.com/theatre-js/theatre/blob/main/packages/r3f/devEnv/bundle.ts#L62-L64)
- [ ] Maybe also worth adding `react` and `react-dom` to the [extension externals list here](https://github.com/theatre-js/theatre/blob/main/packages/r3f/devEnv/bundle.ts#L56-L65)
- [ ] Main bundle externals list doesn't externalize `@react-three/drei`  and `three-stdlib` [here](https://github.com/theatre-js/theatre/blob/main/packages/r3f/devEnv/bundle.ts#L26-L35)

## Screenshots
> This only tests the extension bundle and not the main bundle
### Currently
Running the [esbuild-visualizer](https://www.npmjs.com/package/esbuild-visualizer) on the meta file produced during a build
![Screen Shot 2022-07-06 at 12 39 49 PM](https://user-images.githubusercontent.com/15909884/177602315-697f8030-8ab8-4742-9fd2-70bca0523677.png)

### After adding externals
```
external: [
        '@theatre/core',
        '@theatre/studio',
        '@theatre/dataverse',
        '@theatre/r3f',
        'react',
        'react-dom',
        'three',
        '@react-three/fiber',
        '@react-three/drei',
        'three-stdlib'
],
```
![Screen Shot 2022-07-06 at 12 41 58 PM](https://user-images.githubusercontent.com/15909884/177602495-37bbb0d8-0606-4f8e-9d0b-bbadeb55baa1.png)

**Comment by AriaMinaei** [comment]
Following our chat, I’ll label the issue with “revisit if issue persists” and close it for the time being. If you folks come across a situation where the bundling causes issues, please feel free to re-open.
