### ISSUE TITLE
Ability to select a predefined easing between keyframes (e.g. 'linear')

### ISSUE THREAD

**Issue by jmyrland** [theatre-js/theatre#28]
Feature request based on [this thread](https://discord.com/channels/870988717190426644/889485298575212604/893590264806006804).

The default easing between two keyframes is by default set to `ease-in-out` after inserting a new keyframe. This is fine for most cases, but in some cases it might be useful to provide a way to select another easing between to keyframes, like `linear`.

E.g. when right-clicking the easing-curve between 2 keyframes, it would be nice to present a menu of predefined easing-curves to provide a quick way to set a curve without having to manually adjust the handles.

The prime example for this, is trying to get a perfectly linear curve between two keyframes. Today, if the keyframes are spread far apart, it is quite tricky to get the curve perfectly linear. One workaround is to adjust the state.json manually.

It would be nice to support a predefined set of easing-curves, like how [css have a set of predefined easing functions](https://developer.mozilla.org/en-US/docs/Web/CSS/easing-function):
- `linear [cubic-bezier(0.0, 0.0, 1.0, 1.0)]`
- `ease [cubic-bezier(0.25, 0.1, 0.25, 1.0)]`
- `ease-in [cubic-bezier(0.42, 0.0, 1.0, 1.0)]`
- `ease-in-out [cubic-bezier(0.42, 0.0, 0.58, 1.0)]`
- `ease-out [cubic-bezier(0.0, 0.0, 0.58, 1.0)]`

**Comment by michaeltheory** [comment]
Hoping to be a built helpful and provide a list of cubic beziers we use for our code-based tweening

`{name: 'easeOutCubic', curve: 'cubic-bezier(0.215, 0.610, 0.355, 1.000)'},
{name: 'easeOutQuad', curve: 'cubic-bezier(0.250, 0.460, 0.450, 0.940)'},
{name: 'easeOutQuart', curve: 'cubic-bezier(0.165, 0.840, 0.440, 1.000)'},
{name: 'easeOutQuint', curve: 'cubic-bezier(0.230, 1.000, 0.320, 1.000)'},
{name: 'easeOutSine', curve: 'cubic-bezier(0.390, 0.575, 0.565, 1.000)'},
{name: 'easeOutExpo', curve: 'cubic-bezier(0.190, 1.000, 0.220, 1.000)'},
{name: 'easeOutCirc', curve: 'cubic-bezier(0.075, 0.820, 0.165, 1.000)'},
{name: 'easeOutBack', curve: 'cubic-bezier(0.175, 0.885, 0.320, 1.275)'},

{name: 'easeInCubic', curve: 'cubic-bezier(0.550, 0.055, 0.675, 0.190)'},
{name: 'easeInQuad', curve: 'cubic-bezier(0.550, 0.085, 0.680, 0.530)'},
{name: 'easeInQuart', curve: 'cubic-bezier(0.895, 0.030, 0.685, 0.220)'},
{name: 'easeInQuint', curve: 'cubic-bezier(0.755, 0.050, 0.855, 0.060)'},
{name: 'easeInSine', curve: 'cubic-bezier(0.470, 0.000, 0.745, 0.715)'},
{name: 'easeInCirc', curve: 'cubic-bezier(0.600, 0.040, 0.980, 0.335)'},
{name: 'easeInBack', curve: 'cubic-bezier(0.600, -0.280, 0.735, 0.045)'},

{name: 'easeInOutCubic', curve: 'cubic-bezier(0.645, 0.045, 0.355, 1.000)'},
{name: 'easeInOutQuad', curve: 'cubic-bezier(0.455, 0.030, 0.515, 0.955)'},
{name: 'easeInOutQuart', curve: 'cubic-bezier(0.770, 0.000, 0.175, 1.000)'},
{name: 'easeInOutQuint', curve: 'cubic-bezier(0.860, 0.000, 0.070, 1.000)'},
{name: 'easeInOutSine', curve: 'cubic-bezier(0.445, 0.050, 0.550, 0.950)'},
{name: 'easeInOutExpo', curve: 'cubic-bezier(1.000, 0.000, 0.000, 1.000)'},
{name: 'easeInOutCirc', curve: 'cubic-bezier(0.785, 0.135, 0.150, 0.860)'},
{name: 'easeInOutBack', curve: 'cubic-bezier(0.680, -0.550, 0.265, 1.550)'},

{name: 'easeInOut', curve: 'cubic-bezier(.42,0,.58,1)'},
{name: 'linear', curve: 'linear'}`

**Comment by vezwork** [comment]
This is added in 0.5! Thanks to @michaeltheory for the preset JSON!
