### ISSUE TITLE
[Feat] - Easing - None

### ISSUE THREAD

**Issue by tomorrowevening** [theatre-js/theatre#291]
Ability to choose "no easing" between keyframes, similar to the "hold" keyframe in After Effects

**Comment by tomorrowevening** [comment]
Requesting this be a higher priority, or at least some advice on what files I would need to edit to expose this behavior.
Because the timeline snaps to 30FPS, changing values between "shots" will create a "glitch" state lasting 1 / 30s where you see the interpolation. On devices that render 60/90/120fps, this breaks the illusion in the animation.
An ugly fix is to convert the sequence position to a frame `const frame = Math.round(position * 30)`, and in your `onValuesChange` check if the frame shouldn't update the values

**Comment by friedman74** [comment]
Seconding this request, it can prove to cause critical bugs/glitches in playback that create broken scenes for users.

**Comment by AriaMinaei** [comment]
Closing, since #360 is merged
