### ISSUE TITLE
Logo in Readme is broken

### ISSUE THREAD

**Issue by mslooten** [theatre-js/theatre#296]
The logo in this repo's README.md is pointing to `https://docs.theatrejs.com/public/theatrejs-logo-white.svg` and `https://docs.theatrejs.com/public/theatrejs-logo-black.svg` (depending on dark or light mode), but these don't work for me. I see the docs site has recently changed its URL so perhaps a redirect rule caused this.

Perhaps it's an idea to include the images in this repo?

Happy to create a PR, I think I saw the correct logos in the docs repo. 

EDIT: Just made a small PR, https://github.com/theatre-js/theatre/pull/297

**Comment by AriaMinaei** [comment]
Thanks for the fix @mslooten!
