### ISSUE TITLE
[Bug] - Playground performance

### ISSUE THREAD

**Issue by tomorrowevening** [theatre-js/theatre#325]
`yarn playground` is out to kill my browser, please send help
<img width="830" alt="Screen Shot 2022-10-22 at 12 21 31 PM" src="https://user-images.githubusercontent.com/626143/197359072-87dd8bad-a1fe-4119-abd9-ade50ac5f28f.png">

**Comment by pschroen** [comment]
Same thing with the Vercel builds.

https://theatre-playground.vercel.app/

**Comment by tomorrowevening** [comment]
Just replace the previews with GIFs instead of actually running the code 👍

**Comment by AriaMinaei** [comment]
fixed. thanks ;)
