### ISSUE TITLE
[Bug] - "Sequence" window left the screen

### ISSUE THREAD

**Issue by nikfedotoff** [theatre-js/theatre#327]
![image](https://user-images.githubusercontent.com/46775104/198012572-b26ac563-8255-460d-9dfc-f78bedf3c294.png)

I moved it out of the page, so it's stuck on "top: 1500px" and it was impossible to return window back, because property is fixed and returns on drag

Please limit window movement off screen

**Comment by AriaMinaei** [comment]
This is now fixed. Thanks @nikfedotoff
