### ISSUE TITLE
Support labeled frames and/or framegroups

### ISSUE THREAD

**Issue by RuiOrey** [theatre-js/theatre#33]
Hi, this is a transcription of part of a discord conversation on theatrejs channel, moved here by suggestion of @AriaMinaei .

Basically I'm using the timeline for scrollable website transitions...
so labelling a frame group would probably be the most flexible (it would be possible to name either one frame or several ones) to work with that, instead of having to take note of individual time frame for each transition.
On Flash at least and very probably on other editors, there was an ability to name a keyframe or a range of keyframes.

![image](https://user-images.githubusercontent.com/53763/136452771-27069059-2823-4a8c-af5e-38abb8cab48d.png)

Having that, the usage in terms of `play` or some sort of `playToPosition(frame time or frame name)` api could be something like the following: it would nice to be to be able to say "go to that frame group" either jump there instantaneously **or** playing from the current sequence position.
It could diverge slightly if when the play is triggered was from a frame before or after that frame group 

- if I was on a frame before the frame group it would play until the beginning of the framegroup, 
- if the current position was after, it could play to the end of the framegroup)...

Other parameter for that would be either stop on hitting the framegroup or also playing it through.

well I guess this might sound confusing but feel free to ask me any clarifications

Great work!

**Comment by AriaMinaei** [comment]
This is now being worked on. @vezwork will attach the PR
