### ISSUE TITLE
programatically select a sheet object

### ISSUE THREAD

**Issue by vimlesh1975** [theatre-js/theatre#331]
Sorry for being a new in theatrejs. I cann't find help in satackoverflow or other places. So I write here.
I want to select a sheet object programatically. And when I move a object, props should follow. Please help.
Snapshot does it all automatically but I am not using snapshot. I have my own designer. 
https://vimlesh1975.github.io/three/

**Comment by clementroche** [comment]
You can use `studio.setSelection([someSheet, someObject])` as described in the [docs](https://www.theatrejs.com/docs/0.5/api/studio)

**Comment by vimlesh1975** [comment]
Yes, Thank you.
