### ISSUE TITLE
Ability to collapse namespaces in outline ▶

### ISSUE THREAD

**Issue by juniorxsound** [theatre-js/theatre#356]
### Context 
Right now there's a small triangle next to the namespaces (and other objects too) in the outline view that hints that by clicking it you can collapse it, however it doesn't collapse when clicked. It'd be really helpful to add the ability to collapse namespaces in the outline.
![Screen Shot 2022-12-14 at 12 23 01 PM](https://user-images.githubusercontent.com/15909884/207665110-751b0876-a4b6-4b71-8f22-35344ecab0ab.png)

**Comment by clementroche** [comment]
Seems related to https://github.com/theatre-js/theatre/pull/255

**Comment by clementroche** [comment]
fixed by #367
