### ISSUE TITLE
A color prop

### ISSUE THREAD

**Issue by AriaMinaei** [theatre-js/theatre#38]
Because everyone is asking for it :)

**Comment by tomByrer** [comment]
I found a new color lib that is much faster & smaller than tinycolor2:
https://github.com/omgovich/colord

Not sure if it should be included, or theatre have just 1 color format (hex?) then document how users can use an external library to translate color spaces or format?

**Comment by vezwork** [comment]
A color prop has been added in 0.5! I won't close this issue yet because people may have more to say about the color prop.

**Comment by AriaMinaei** [comment]
Let's close as resolved :)
