### ISSUE TITLE
How to clear the state of a project (originally: make all static programatically)

### ISSUE THREAD

**Issue by vimlesh1975** [theatre-js/theatre#382]
Is there any method to do it?

**Comment by gmile** [comment]
@vimlesh1975 could you elaborate what is your use case to give more context?

**Comment by clementroche** [comment]
I think @vimlesh1975 is asking for a prop static option so you couldn't create a timeline from it.

**Comment by vimlesh1975** [comment]
After finishing one project, I want to start new project but objects are same. So I need to reset all animations at one go.
[https://jsfiddle.net/vimlesh1975/webh6gsx/2/](url)

**Comment by AriaMinaei** [comment]
@vimlesh1975 hmm, if a project is finished, I'd assume the new project would need a different ID. Would changing the project id help? `getProject(newId)` I mean.

**Comment by clementroche** [comment]
delete your state and do a localeStorage.clear()

**Comment by vimlesh1975** [comment]
> @vimlesh1975 hmm, if a project is finished, I'd assume the new project would need a different ID. Would changing the project id help? `getProject(newId)` I mean.

Yes changing the project id clears everything. So can I do it programatically?

**Comment by vimlesh1975** [comment]
Basically I need like 
` const onMousedblclick = (obj, event) => {
                        studio.transaction(({ unset }) => {
                            unset(obj.props);
                            unset(obj.animations); //not available
                        });
                    };`

**Comment by vimlesh1975** [comment]
> delete your state.json and do a localeStorage.clear()
following did the job.
Thank you.
`localStorage.clear();
 location.reload();`

**Comment by AriaMinaei** [comment]
Thanks @clementroche!
@vimlesh1975 I'll mark this one as solved, but feel free to re-open if the localStorage clearing method isn't enough.
