### ISSUE TITLE
@theatre/r3f extension breaks with vite

### ISSUE THREAD

**Issue by MartinEmanuelMaldonado93** [theatre-js/theatre#439]
the extension breaks and don't know why 

https://stackblitz.com/edit/vitejs-vite-2f3xa3?file=src%2FApp.tsx&terminal=dev

any idea?

**Comment by aelsayd** [comment]
@MartinEmanuelMaldonado93 I am running into the same issue, how did you resolve it?

**Comment by MartinEmanuelMaldonado93** [comment]
Yeah I've done the same and it works
