### ISSUE TITLE
Free 3D studio built with BabylonJS and Theatre-JS

### ISSUE THREAD

**Issue by wahono77** [theatre-js/theatre#454]
Free 3D studio built with BabylonJS (https://www.babylonjs.com/) and combined with this great animation platform Theatre-JS to build complex animations.

**Binwa3D Features:**

* Free
* Without any installation, run directly from browser
* Support desktop and mobile
* Run from any operating system
* Realistic 3D effect i.e reflection texture, support PBR textures
* Free 3D models for speed up your production
* Create realistic 3D text using various fonts
* Convert any 2D SVG file to 3D object
* Support material from Web Camera video
* Support material from video URL file (MP4, WebM, OGV)
* Easy animate any object
* Save screenshot as image file
* Save animation to video (Webm)

Please visit to https://binwa3d.com/

Thanks To Theatre-JS Team

**Comment by AriaMinaei** [comment]
Wow, lots of features! And thanks for dropping a note here :)

My main suggestion is to use a UI library for UI consistency. I hear great things about [shadcn/ui](https://ui.shadcn.com/).

Also something I noticed is that the user has to seek the sequence back to `0second` before going back to design mode. `sheet.sequence.position = 0` would do the same.
