### ISSUE TITLE
animation frozen when enter into immersive AR or VR mode on Quest browser

### ISSUE THREAD

**Issue by jerryhou77** [theatre-js/theatre#477]
We use theatre.js on a-frame (based on three.js) 3D web page, it works well on PC and Quest browser flat mode, but when we enter AR or VR mode, the aninmation froze, when we exit the immersive mode to flat mode , the animation can continue play. is this an issue, or the theatre.js did not support AR / VR mode from begining, thanks.

**Comment by AriaMinaei** [comment]
@jerryhou77 For VR/AR, you should use a custom [`rafDriver`](https://www.theatrejs.com/docs/latest/manual/advanced#rafdrivers) since immersive mode doesn't use the main window's `requestAnimatinFrame` loop.

Feel free to ask on [Discord](https://discord.gg/bm9f8F9Y9N) :)
