### ISSUE TITLE
Feature request: Copy+Paste keyframes

### ISSUE THREAD

**Issue by fulopkovacs** [theatre-js/theatre#68]
## Description
It would be great to be able to copy and paste keyframes, since it's a feature that I use quite a lot when I create loops (and some other times too).

## Implementation

UX-wise the easiest solution might be adding new items (`Copy Keyframe`, `Paste Keyframe`) to the context menu that appears when the user right clicks on a keyframe in the sequence editor (right now (`"@theatre/studio": "0.4.7"`) it's just contains one item: `Delete Keyframe`).

<img width="848" alt="image" src="https://user-images.githubusercontent.com/43729152/152785701-6388ecc0-be61-4034-964d-528b98feac14.png">

**Comment by danvoyce** [comment]
Hey @fulopkovacs thanks for creating this feature request. This is something a lot of our users are requesting, and I've already started working on. I'll be opening up a PR for it soon so any feedback would be great!

**Comment by fulopkovacs** [comment]
Awesome, thank you for the response @danvoyce . Could you tag me in a comment under the PR when it's open? I'd be happy to check it out and share my thoughts about it! ☺️

**Comment by vezwork** [comment]
Hey @fulopkovacs can you confirm that my PRs #105 and #107 fulfill what you are looking for in this issue? If so, let's close this issue!

**Comment by fulopkovacs** [comment]
@vezwork Yepp, I think this was it! Thanks for the solution! ☺️
