### ISSUE TITLE
Feature request: Select multiple keyframes with the mouse in the Sequence Editor

### ISSUE THREAD

**Issue by fulopkovacs** [theatre-js/theatre#69]
## Description

There are times when I want to move multiple keyframes at once in the sequence editor. These times I instinctively try to make a rectangle selection with the mouse, which moves the playhead here.

## Implementation

Here's a rough sketch of the rectangle selection tool to illustrate my point:

![select-multiple-frames](https://user-images.githubusercontent.com/43729152/152789414-e263a99a-877d-484e-9719-a2d068ef83da.png)

I haven't thought about how to resolve the conflict between moving the playhead and the multiple keyframe selection tool yet.

**Comment by danvoyce** [comment]
Hey @fulopkovacs this feature already exists. Not super obvious, but try holding down shift when dragging.

Let us know if you have any ideas on how to improve this / make it more obvious (apart from adding it to the docs)

**Comment by fulopkovacs** [comment]
Awesome! I quickly tried it, and this is what I needed! :relaxed: 

About making this feature more discoverable: there's a UX-pattern that I have recently fallen in love with. I don't know the name, but it's basically displaying the relevant modifier keys and their effects on the bottom of the screen. It's not new, and I'm sure that you'rere already familiar with it, but here are a few examples:

## Affinity Designer

<img width="610" alt="affinity-designer-2" src="https://user-images.githubusercontent.com/43729152/152989187-a6446f7a-5550-4bf8-bf5f-cba8882b71e1.png">

<img width="747" alt="affinity-designer-1" src="https://user-images.githubusercontent.com/43729152/152989205-cd9e0431-dac2-4113-9d38-bd2f08ae62d6.png">

## Inkscape

(Btw I never thought I'd ever bring up Inkscape in a UX-related discussion... :laughing: )

![image](https://user-images.githubusercontent.com/43729152/152989407-25badd84-6620-4d95-880e-c98ca2d7598a.png)
![image](https://user-images.githubusercontent.com/43729152/152989443-91cb5e20-f542-4f35-bf95-1cb4557681c9.png)

In Inkscape when you press a modifier key, you can see what it does (depending what tool you use and the position of the cursor). I pressed `Shift` in the screenshot below:

![inkscape-1](https://user-images.githubusercontent.com/43729152/152990465-869999a2-37b1-4e76-9543-85028f81acc8.png)

## Blender

In Blender the help text depends on the currently active tool and the pressed modifier(s).

Here's a screenshot with no modifier keys pressed:

![image](https://user-images.githubusercontent.com/43729152/152991158-5fc513aa-3902-4a23-915e-986ef1196481.png)

And this is how it looks like with the `Shift` key pressed:

![image](https://user-images.githubusercontent.com/43729152/152991984-bdbcebc3-1294-4088-b2e0-d9ccb9fe5681.png)

There might be better examples of this UX pattern out there, but these were the programs that i could quickly open for a screenshot. Something like this would be really helpful, especially in the future, when `Theatre.js` uses even more modifier keys. I do recognize however, that keyboard shortcuts and modifier keys are not easy to implement, since you have to know what other programs your users use (Adobe Creative Suite, Blender, Maya, C4D, etc...) to avoid the keystroke-confusion-hell.... :laughing: 

Anyways, this issue can be closed, thank you  for your help!

**Comment by danvoyce** [comment]
Thanks @fulopkovacs for these examples. I had completely forgotten about this idea as I don't spend as much time using these tools as I'd like to.

Watch this space!
