### ISSUE TITLE
The playhead is not lined up with the frames in the Time Sequence Editor (Firefox on Windows and Linux)

### ISSUE THREAD

**Issue by fulopkovacs** [theatre-js/theatre#90]
There are no errors in the console.

## Details
| OS | Firefox version | Other Specs/Comments |
| --- | --- | --- |
| Windows  10 (19041.1415) | 97.0.1 (newest) | Old, low-spec laptop, no dedicated GPU or anything fancy like that |
| Manjaro Linux | 97.0 | Has a GPU: NVIDIA GeForce RTX 2060 SUPER | 

## Picture about the issue
This is how the issue looks like on the Windows machine:

![034D753C-138E-4887-A06E-AD8A18F9477A](https://user-images.githubusercontent.com/43729152/156313536-05fe8ae4-03ea-4958-b143-dde5c66ab6d5.png)

**Comment by fulopkovacs** [comment]
> @fulopkovacs if you are able to re-test this, I have modified the way keyframes are offset from the left. It is possible it is related to this issue and may have made a difference.

:+1:  Nice, it works on Linux! Will check this out on Windows, once I got my hands on it...

**Comment by lchsam** [comment]
Hi, I think we can close this issue. https://github.com/theatre-js/theatre/commit/ca5b2685bb340875ebf68092f6cb8e82cf9e674c fixes this and it's already included in versions [0.4.8-dev.3](https://github.com/theatre-js/theatre/releases/tag/0.4.8-dev.3) and up.

**Comment by lchsam** [comment]
Hi, I think https://github.com/theatre-js/theatre/commit/ca5b2685bb340875ebf68092f6cb8e82cf9e674c fixes this and it's already included in versions [0.4.8-dev.3](https://github.com/theatre-js/theatre/releases/tag/0.4.8-dev.3) and up.

**Comment by AriaMinaei** [comment]
Yes, will close then. Thanks @Ichsam!
