### ISSUE TITLE
The playground projects must include a index.tsx file, otherwise they won't be displayed on the project selector page

### ISSUE THREAD

**Issue by fulopkovacs** [theatre-js/theatre#91]
## Issue

It seems like all the projects in `packages/playground/src/personal` (and also `shared`) should have an `index.tsx` as an entry point, otherwise they won't show up in the list of playgrounds when the server is started. (Check out this line and its context  if you want to see why: https://github.com/theatre-js/theatre/blob/c919aa2f22f43939ebe19ae65482015293474d81/packages/playground/src/index.tsx#L15)

All of these projects for example contain an `index.tsx` file:

```sh
$ ls -1 packages/playground/src/*/*/index.tsx
packages/playground/src/personal/bouncing-boxes/index.tsx
packages/playground/src/shared/dom/index.tsx
packages/playground/src/shared/r3f-rocket/index.tsx
packages/playground/src/shared/turtle/index.tsx
packages/playground/src/tests/setting-static-props/index.tsx
```

![image](https://user-images.githubusercontent.com/43729152/156329641-3f8cc90b-c1e1-4054-a360-5291ed8ffdff.png)

## Suggested solution

Add a note to  `/home/fulop/theatre-js/theatre/packages/playground/README.md` about this behavior.,

**Comment by AriaMinaei** [comment]
Yeah feel free to update the readme https://github.com/theatre-js/theatre/blob/main/packages/playground/README.md

**Comment by fulopkovacs** [comment]
Okay, I will! I just wasn't sure if this is what we want to happen in the future. Eventually we might add plain HTML or Vue tests and projects, right?

**Comment by AriaMinaei** [comment]
We can change this setup as soon as we have use cases that it can't support. Right now I can't think of any such use-case though.
